frr version 9.1
frr defaults traditional
hostname leaf-03
agentx
!
interface lo
 ip address 10.255.0.23/32
!
interface eth1
 description uplink-to-spine-01
 ip address 10.101.3.2/30
!
interface eth2
 description uplink-to-spine-02
 ip address 10.101.6.2/30
!
interface vxlan100
!
router bgp 65003
 bgp router-id 10.255.0.23
 neighbor 10.101.3.1 remote-as 65000
 neighbor 10.101.3.1 timers connect 10
 neighbor 10.101.6.1 remote-as 65000
 neighbor 10.101.6.1 timers connect 10
 !
 address-family ipv4 unicast
  network 10.255.0.23/32
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 10.101.3.1 activate
  neighbor 10.101.6.1 activate
  advertise-all-vni
  advertise ipv4 unicast
 exit-address-family
!
